// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Init_Doctor_Patient_Assistant_Appoinment_Prescription_PrescriptionDetail__with_dummy_data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init_Doctor_Patient_Assistant_Appoinment_Prescription_PrescriptionDetail__with_dummy_data));
        
        string IMigrationMetadata.Id
        {
            get { return "202308140340098_Init_Doctor_Patient_Assistant_Appoinment_Prescription_PrescriptionDetail__with_dummy_data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
