// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Init_Health_Detail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init_Health_Detail));
        
        string IMigrationMetadata.Id
        {
            get { return "202308240016255_Init_Health_Detail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
