// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Added_encrypted_password_to_doctor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_encrypted_password_to_doctor));
        
        string IMigrationMetadata.Id
        {
            get { return "202308220220030_Added_encrypted_password_to_doctor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
